    name: GitHub Classroom Workflow

    on: [push]

    jobs:
      build:
        name: Autograding
        runs-on: ubuntu-latest
        steps:
             - uses: actions/checkout@v2
             - uses: actions/setup-dotnet@v1
               with:
                    dotnet-version: '3.1.x' # SDK Version to use; x will use the latest version of the 3.1 channel 
             - run: dotnet test
               working-directory: ./HelloWorld
             - uses: education/autograding@v1\
               env:
                   DOTNET_CLI_HOME: ./HelloWorld
             
               
